---
# tasks file for hostname
- name: Install requirements
  package:
    name: '{{ hostname_requirements }}'
    state: present
  register: hostname_install_requirements
  when: ansible_distribution | lower != 'coreos'
  until: hostname_install_requirements is succeeded
  retries: 3

- name: Set hostname
  hostname:
    name: '{{ hostname }}'
  when:
    - ansible_virtualization_type != "docker"
  register: set_hostname

- name: Reboot for hostname
  include_role:
    name: reboot
  when:
    - set_hostname.changed
    - hostname_reboot | bool
  tags:
    - skip_ansible_lint
